import express from 'express';
import {
  getCashFlow,
  createSalarySlip,
  getSalarySlips,
  markSalaryPaid,
  getMySalarySlips,
} from '../controllers/financeController.js';
import { authenticate, requireRole } from '../middleware/auth.js';

const router = express.Router();

router.use(authenticate);

// Any authenticated staff member / admin: view my own salary slips (generated by the
// accountant). Must be declared before the accountant/admin-only routes below.
router.get('/my-salary-slips', getMySalarySlips);

router.get('/cashflow', requireRole('accountant', 'admin'), getCashFlow);

router.post('/salary-slips', requireRole('accountant', 'admin'), createSalarySlip);
router.get('/salary-slips', requireRole('accountant', 'admin'), getSalarySlips);
router.patch('/salary-slips/:id/pay', requireRole('accountant', 'admin'), markSalaryPaid);

export default router;
