import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { apiFetch } from "../api.js";
import { useAuth } from "../AuthContext.jsx";
import { AdminLayout } from "../components/AdminLayout.jsx";
import "./Dashboard.css";
import "./AdminDashboard.css";
import "../components/AdminShared.css";

function formatDate(value){if(!value)return "—";try{return new Date(value).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}catch{return String(value)}}
function Icon({name,size=18}){const p={users:<><circle cx="9" cy="8" r="3"/><path d="M3 20a6 6 0 0 1 12 0M15 6a3 3 0 0 1 0 6M17 14a6 6 0 0 1 4 5"/></>,message:<path d="M20 11.5a7.5 7.5 0 0 1-7.5 7.5H7l-4 3v-6.1a7.5 7.5 0 1 1 17-4.4Z"/>,calendar:<><rect x="3" y="4.5" width="18" height="17" rx="2"/><path d="M16 2.5v4M8 2.5v4M3 9h18"/></>,wallet:<><path d="M4 6.5A2.5 2.5 0 0 1 6.5 4H20v16H6a3 3 0 0 1-3-3V7"/><path d="M3 8h15M16 13h4"/></>,truck:<><path d="M3 7h11v9H3z"/><path d="M14 11h4l3 3v2h-7z"/><circle cx="7.5" cy="18" r="1.6"/><circle cx="17.5" cy="18" r="1.6"/></>,star:<path d="m12 3 2.6 5.6 6.1.7-4.5 4.2 1.2 6-5.4-3-5.4 3 1.2-6-4.5-4.2 6.1-.7Z"/>};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>}

const TABS=[{id:"overview",label:"Overview"},{id:"enquiries",label:"Enquiries"},{id:"users",label:"Users"}];
export default function AdminDashboard(){
 const {user}=useAuth(); const [tab,setTab]=useState("overview"); const [stats,setStats]=useState(null); const [statsLoading,setStatsLoading]=useState(true); const [enquiries,setEnquiries]=useState([]); const [users,setUsers]=useState([]); const [loading,setLoading]=useState(true); const [analytics,setAnalytics]=useState([]);
 const load=useCallback(async()=>{setStatsLoading(true);setLoading(true);const [s,e,u,a]=await Promise.all([apiFetch("/api/admin/stats"),apiFetch("/api/enquiry?limit=50"),apiFetch("/api/admin/users?limit=50"),apiFetch("/api/admin/analytics?days=7")]);if(s.ok&&s.data?.success)setStats(s.data.stats);if(e.ok&&e.data?.success)setEnquiries(e.data.enquiries||[]);if(u.ok&&u.data?.success)setUsers(u.data.users||[]);if(a.ok&&a.data?.success)setAnalytics(a.data.series||[]);setStatsLoading(false);setLoading(false)},[]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{let cancelled=false; apiFetch(`/api/admin/analytics?days=${overviewPeriod === "month" ? 30 : 7}`).then((r)=>{if(!cancelled&&r.ok&&r.data?.success)setAnalytics(r.data.series||[])}).catch(()=>{}); return ()=>{cancelled=true}},[overviewPeriod]);
 const counts=useMemo(()=>{const out={NEW:0,IN_REVIEW:0,CONTACTED:0,QUOTED:0,CONVERTED:0,CANCELLED:0,CLOSED:0};enquiries.forEach(e=>{const k=String(e.status||"NEW").toUpperCase();out[k]=(out[k]||0)+1});return out},[enquiries]);
 const attention=(stats?.newEnquiries||0)+(stats?.inReviewEnquiries||0)+(stats?.maintenanceVehicles||0);
 const chartMax=Math.max(1,...analytics.flatMap((d)=>[d.enquiries||0,d.bookings||0]));
 const toPoints=(key)=>analytics.map((d,i)=>{const x=analytics.length===1?280:(i*560/(analytics.length-1));const y=170-((d[key]||0)/chartMax)*145;return `${x.toFixed(1)},${Math.max(15,y).toFixed(1)}`}).join(" ");
 const statusTotal=Math.max(1,enquiries.length);
 const newPct=(counts.NEW/statusTotal)*100; const followPct=((counts.CONTACTED+counts.IN_REVIEW)/statusTotal)*100; const bookingPct=((counts.QUOTED+counts.CONVERTED)/statusTotal)*100; const cancelledPct=(counts.CANCELLED/statusTotal)*100;
 const donutStyle={background:`conic-gradient(#2f79e8 0 ${newPct}%,#f1b53d ${newPct}% ${newPct+followPct}%,#42ad73 ${newPct+followPct}% ${newPct+followPct+bookingPct}%,#f25c63 ${newPct+followPct+bookingPct}% 100%)`};
 if(!user)return null;
 return <AdminLayout title="Dashboard" lead={`Signed in as +91 ${user.phone} · ${user.role.replace(/_/g," ")}`}>
   <div className="admin-dashboard-actions"><div className="admin-tabs">{TABS.map(t=><button key={t.id} type="button" className={`admin-tab ${tab===t.id?"admin-tab-active":""}`} onClick={()=>setTab(t.id)}>{t.label}</button>)}</div><div className="admin-action-links"><Link to="/admin/bookings/create" className="btn btn-primary btn-sm">+ Create booking</Link></div></div>
   {tab==="overview"&&<>
     <div className="hospital-admin-kpis">
       <div className="hospital-kpi"><span className="hospital-kpi-icon blue"><Icon name="message"/></span><div><small>Total Enquiries</small><strong>{statsLoading?"…":stats?.totalEnquiries??"—"}</strong><em>Live enquiries</em></div></div>
       <div className="hospital-kpi"><span className="hospital-kpi-icon green"><Icon name="calendar"/></span><div><small>Total Bookings</small><strong>{statsLoading?"…":stats?.totalBookings??"—"}</strong><em>All bookings</em></div></div>
       <div className="hospital-kpi"><span className="hospital-kpi-icon violet"><Icon name="users"/></span><div><small>Total Customers</small><strong>{statsLoading?"…":stats?.totalCustomers??"—"}</strong><em>Registered users</em></div></div>
       <div className="hospital-kpi"><span className="hospital-kpi-icon orange"><Icon name="wallet"/></span><div><small>Attention Items</small><strong>{statsLoading?"…":attention}</strong><em>Need follow-up</em></div></div>
     </div>
     <div className="hospital-admin-main-grid">
       <section className="hospital-admin-panel"><div className="hospital-panel-head"><h3>Enquiries &amp; Bookings Overview</h3><select value={overviewPeriod} onChange={(e)=>setOverviewPeriod(e.target.value)} aria-label="Overview period"><option value="week">This Week</option><option value="month">This Month</option></select></div><div className="hospital-line-chart"><div className="chart-y"><span>{chartMax}</span><span>{Math.round(chartMax*.8)}</span><span>{Math.round(chartMax*.6)}</span><span>{Math.round(chartMax*.4)}</span><span>{Math.round(chartMax*.2)}</span><span>0</span></div><div className="chart-area"><svg viewBox="0 0 560 190" preserveAspectRatio="none"><g className="chart-grid"><path d="M0 20H560M0 54H560M0 88H560M0 122H560M0 156H560"/></g>{analytics.length>0 && <><polyline className="chart-line blue" points={toPoints("enquiries")}/><polyline className="chart-line green" points={toPoints("bookings")}/></>}</svg><div className="chart-labels">{analytics.map((d)=><span key={d.date}>{d.label}</span>)}</div></div></div><div className="chart-legend"><span><i className="blue-dot"/> Enquiries</span><span><i className="green-dot"/> Bookings</span></div></section>
       <section className="hospital-admin-panel status-panel"><div className="hospital-panel-head"><h3>Enquiry Status</h3></div><div className="donut-wrap"><div className="donut" style={donutStyle}><div className="donut-hole">{enquiries.length}</div></div><div className="status-list"><span><i className="s-blue"/>New <b>{counts.NEW}</b></span><span><i className="s-orange"/>Follow Up <b>{counts.CONTACTED+counts.IN_REVIEW}</b></span><span><i className="s-green"/>For Booking <b>{counts.QUOTED+counts.CONVERTED}</b></span><span><i className="s-red"/>Cancelled <b>{counts.CANCELLED}</b></span></div></div></section>
     </div>
     <section className="hospital-admin-panel recent-admin-panel"><div className="hospital-panel-head"><h3>Recent Enquiries</h3><Link to="/admin/enquiries">View All</Link></div><div className="hospital-admin-table-wrap"><table className="hospital-admin-table"><thead><tr><th>Name</th><th>Phone</th><th>Package / Vehicle</th><th>Status</th><th>Date</th></tr></thead><tbody>{enquiries.slice(0,5).map((e,i)=><tr key={e.id||e._id||i}><td>{e.name||"—"}</td><td>{e.phone||"—"}</td><td>{e.vehicleName||e.packageName||e.vehicle?.name||e.tourPackage?.name||"Travel enquiry"}</td><td><span className={`admin-status status-${String(e.status||"NEW").toLowerCase()}`}>{String(e.status||"NEW").replace(/_/g," ")}</span></td><td>{formatDate(e.createdAt||e.created_at||e.date)}</td></tr>)}</tbody></table>{!enquiries.length&&!loading&&<p className="admin-empty-note">No enquiries yet.</p>}</div></section>
     <div className="hospital-admin-bottom-kpis"><div><span><Icon name="truck"/></span><small>Total Vehicles</small><strong>{statsLoading?"…":stats?.activeVehicles??"—"}</strong><em>Active vehicles</em></div><div><span><Icon name="calendar"/></span><small>Total Trips</small><strong>{statsLoading?"…":stats?.totalBookings??"—"}</strong><em>Active trips</em></div><div><span><Icon name="users"/></span><small>Total Customers</small><strong>{statsLoading?"…":stats?.totalCustomers??"—"}</strong><em>Registered users</em></div><div><span><Icon name="star"/></span><small>Total Reviews</small><strong>{statsLoading?"…":stats?.approvedReviews??"—"}</strong><em>Approved reviews</em></div></div>
   </>}
   {tab==="enquiries"&&<section className="hospital-admin-panel"><div className="hospital-panel-head"><h3>All Enquiries</h3><Link to="/admin/enquiries">Open management</Link></div><div className="hospital-admin-table-wrap"><table className="hospital-admin-table"><thead><tr><th>Name</th><th>Phone</th><th>Package / Vehicle</th><th>Status</th><th>Date</th></tr></thead><tbody>{enquiries.map((e,i)=><tr key={e.id||e._id||i}><td>{e.name||"—"}</td><td>{e.phone||"—"}</td><td>{e.vehicleName||e.packageName||"Travel enquiry"}</td><td><span className="admin-status">{String(e.status||"NEW").replace(/_/g," ")}</span></td><td>{formatDate(e.createdAt)}</td></tr>)}</tbody></table></div></section>}
   {tab==="users"&&<section className="hospital-admin-panel"><div className="hospital-panel-head"><h3>Users</h3><Link to="/admin/customers">Open customer management</Link></div><div className="hospital-admin-table-wrap"><table className="hospital-admin-table"><thead><tr><th>Name</th><th>Phone</th><th>Role</th><th>Status</th></tr></thead><tbody>{users.slice(0,12).map((u,i)=><tr key={u.id||u._id||i}><td>{u.name||"Unnamed user"}</td><td>{u.phone||"—"}</td><td>{u.role||"customer"}</td><td><span className="admin-status">{u.isActive===false?"Inactive":"Active"}</span></td></tr>)}</tbody></table></div></section>}
 </AdminLayout>
}
