import { useCallback, useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { apiFetch, API_URL } from "../../api.js";
import { AdminLayout } from "../../components/AdminLayout.jsx";

function formatDate(value) {
  if (!value) return "—";
  return new Date(value).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

function PaymentBadge({ invoice }) {
  if (invoice.status === "VOID") {
    return <span className="admin-badge admin-badge-void">Void</span>;
  }
  if (Number(invoice.balance) <= 0) {
    return <span className="admin-badge admin-badge-paid">Paid</span>;
  }
  return <span className="admin-badge admin-badge-pending">Pending</span>;
}

export default function AdminInvoices() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [invoices, setInvoices] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const search = searchParams.get("search") || "";

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    const params = new URLSearchParams();
    if (search) params.set("search", search);
    const { ok, data } = await apiFetch(`/api/admin/invoices?${params.toString()}`);
    if (ok && data?.success) {
      setInvoices(data.invoices);
      setTotal(data.total);
    } else {
      setError(data?.error || "Failed to load invoices.");
    }
    setLoading(false);
  }, [search]);

  useEffect(() => {
    load();
  }, [load]);

  return (
    <AdminLayout title="Invoices" lead="Invoices are generated by SuperAdmin from a confirmed booking.">
      <div className="admin-page-actions">
        <p className="admin-subtext">{total} invoice{total === 1 ? "" : "s"}</p>
      </div>

      <div className="ticket admin-table-card" style={{ marginBottom: "1rem" }}>
        <div className="admin-form-field">
          <label className="otp-label-text" htmlFor="inv-search">Search</label>
          <input
            id="inv-search"
            className="admin-input"
            placeholder="Invoice number or customer name"
            defaultValue={search}
            onKeyDown={(e) => e.key === "Enter" && setSearchParams({ search: e.target.value })}
            onBlur={(e) => setSearchParams({ search: e.target.value })}
          />
        </div>
      </div>

      <div className="ticket admin-table-card">
        {loading ? (
          <p className="admin-loading">Loading invoices…</p>
        ) : error ? (
          <p className="admin-error">{error}</p>
        ) : invoices.length === 0 ? (
          <div className="admin-empty">
            <strong>No invoices yet</strong>
            <p className="admin-subtext">Invoices generated from confirmed bookings will appear here.</p>
          </div>
        ) : (
          <div className="admin-table-wrap">
            <table className="admin-table">
              <thead>
                <tr>
                  <th>Invoice #</th>
                  <th>Customer</th>
                  <th>Date</th>
                  <th>Total</th>
                  <th>Balance</th>
                  <th>Status</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                {invoices.map((inv) => (
                  <tr key={inv.id}>
                    <td>{inv.invoiceNumber}</td>
                    <td>{inv.customer?.name}</td>
                    <td>{formatDate(inv.invoiceDate)}</td>
                    <td>₹{inv.total}</td>
                    <td>₹{inv.balance}</td>
                    <td>
                      <PaymentBadge invoice={inv} />
                    </td>
                    <td>
                      <div className="admin-row-actions">
                        <Link to={`/admin/invoices/${inv.id}`} className="admin-inline-btn">View</Link>
                        <a
                          className="admin-inline-btn"
                          href={`${API_URL}/api/admin/invoices/${inv.id}/pdf`}
                          target="_blank"
                          rel="noreferrer"
                        >
                          Download
                        </a>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </AdminLayout>
  );
}
