import { useEffect, useState } from "react";
import { apiFetch } from "../../api.js";
import { AdminLayout } from "../../components/AdminLayout.jsx";
import "./AdminTourPackages.css";

const blank = { title:"", destination:"", durationDays:1, priceFrom:0, description:"", itinerary:"", inclusions:"", exclusions:"", imageUrl:"", isActive:true, featured:false, priority:0 };
const csv = (v) => String(v || "").split("\n").map(x=>x.trim()).filter(Boolean);
export default function AdminTourPackages() {
  const [items,setItems]=useState([]), [form,setForm]=useState(blank), [editing,setEditing]=useState(null), [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState("");
  const load=()=>{setLoading(true);apiFetch("/api/tour-packages/admin").then(({ok,data})=>{if(ok&&data?.success)setItems(data.packages||[]);else setError(data?.error||"Failed to load packages.")}).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const edit=(p)=>{setEditing(p.id);setForm({...p,itinerary:(p.itinerary||[]).join("\n"),inclusions:(p.inclusions||[]).join("\n"),exclusions:(p.exclusions||[]).join("\n")});window.scrollTo({top:0,behavior:"smooth"});};
  const reset=()=>{setEditing(null);setForm(blank);setError("")};
  const save=async(e)=>{e.preventDefault();setSaving(true);setError("");const body={...form,durationDays:Number(form.durationDays),priceFrom:Number(form.priceFrom),priority:Number(form.priority),itinerary:csv(form.itinerary),inclusions:csv(form.inclusions),exclusions:csv(form.exclusions)};const r=await apiFetch(editing?`/api/tour-packages/admin/${editing}`:"/api/tour-packages/admin",{method:editing?"PATCH":"POST",body:JSON.stringify(body)});setSaving(false);if(!r.ok||!r.data?.success){setError(r.data?.error||"Unable to save package.");return;}reset();load();};
  const remove=async(id)=>{if(!confirm("Delete this tour package?"))return;const r=await apiFetch(`/api/tour-packages/admin/${id}`,{method:"DELETE"});if(!r.ok) setError(r.data?.error||"Unable to delete package.");else load();};
  return <AdminLayout title="Tour Packages" lead="Create and manage the travel packages shown to customers."><div className="admin-page-actions"><p className="admin-subtext">{items.length} package{items.length===1?"":"s"}</p><button className="btn btn-primary btn-sm" onClick={()=>{reset();window.scrollTo({top:0,behavior:"smooth"})}}>+ Add package</button></div>{error&&<p className="otp-error">{error}</p>}
  <form className="ticket admin-package-form" onSubmit={save}><div className="admin-package-form-head"><div><p className="eyebrow">{editing?"Edit package":"New package"}</p><h2>{editing?"Update tour package":"Create a tour package"}</h2></div>{editing&&<button type="button" className="btn btn-outline btn-sm" onClick={reset}>Cancel</button>}</div><div className="admin-form-grid"><Field label="Package title" value={form.title} onChange={v=>setForm({...form,title:v})}/><Field label="Destination" value={form.destination} onChange={v=>setForm({...form,destination:v})}/><Field label="Duration (days)" type="number" value={form.durationDays} onChange={v=>setForm({...form,durationDays:v})}/><Field label="Starting price" type="number" value={form.priceFrom} onChange={v=>setForm({...form,priceFrom:v})}/><Field label="Image URL" value={form.imageUrl} onChange={v=>setForm({...form,imageUrl:v})}/><Field label="Priority" type="number" value={form.priority} onChange={v=>setForm({...form,priority:v})}/></div><label className="admin-form-field"><span className="otp-label-text">Description</span><textarea className="admin-textarea" rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="admin-form-grid"><ListField label="Itinerary (one line per day)" value={form.itinerary} onChange={v=>setForm({...form,itinerary:v})}/><ListField label="Inclusions" value={form.inclusions} onChange={v=>setForm({...form,inclusions:v})}/><ListField label="Exclusions" value={form.exclusions} onChange={v=>setForm({...form,exclusions:v})}/></div><div className="admin-checks"><label><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><label><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label></div><button className="btn btn-primary" disabled={saving}>{saving?"Saving…":editing?"Update package":"Create package"}</button></form>
  <div className="ticket admin-table-card">{loading?<p className="admin-loading">Loading tour packages…</p>:items.length===0?<p className="admin-empty">No tour packages yet.</p>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Package</th><th>Destination</th><th>Duration</th><th>Price</th><th>Status</th><th>Actions</th></tr></thead><tbody>{items.map(p=><tr key={p.id}><td><strong>{p.title}</strong><p className="admin-subtext">{p.featured?"Featured · ":""}{p.slug}</p></td><td>{p.destination}</td><td>{p.durationDays} days</td><td>₹{Number(p.priceFrom||0).toLocaleString("en-IN")}</td><td><span className={`admin-badge ${p.isActive?"admin-badge-active":"admin-badge-inactive"}`}>{p.isActive?"Active":"Inactive"}</span></td><td><button className="admin-inline-btn" onClick={()=>edit(p)}>Edit</button> <button className="admin-inline-btn" onClick={()=>remove(p.id)}>Delete</button></td></tr>)}</tbody></table></div>}</div></AdminLayout>;
}
function Field({label,value,onChange,type="text"}){return <label className="admin-form-field"><span className="otp-label-text">{label}</span><input className="admin-input" type={type} value={value} onChange={e=>onChange(e.target.value)} required={label!="Image URL"}/></label>}
function ListField({label,value,onChange}){return <label className="admin-form-field"><span className="otp-label-text">{label}</span><textarea className="admin-textarea" rows="6" value={value} onChange={e=>onChange(e.target.value)} placeholder="One item per line"/></label>}
